{% set tpl = ix_lib.base.render.Render(values) %}

{% set c = tpl.add_container(values.consts.linkwarden_container_name, "image") %}
{% set meili = tpl.add_container(values.consts.meilisearch_container_name, "meilisearch_image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.linkwarden.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(
  values.consts.postgres_container_name,
  values.linkwarden.postgres_image_selector,
  pg_config, perm_container
) %}

{% do meili.set_user(values.run_as.user, values.run_as.group) %}
{% do meili.healthcheck.set_test("curl", {"port": values.consts.meilisearch_port, "path": "/health"}) %}
{% do meili.environment.add_env("MEILI_MASTER_KEY", values.linkwarden.meilisearch_master_key) %}
{% do meili.environment.add_env("DEFAULT_HTTP_ADDR", "0.0.0.0:%d"|format(values.consts.meilisearch_port)) %}
{% do meili.environment.add_env("MEILI_NO_ANALYTICS", true) %}
{% do meili.environment.add_env("MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE", true) %}

{% do meili.add_storage("/meili_data", values.storage.meili_data) %}
{% do perm_container.add_or_skip_action("meili-data", values.storage.meili_data, perms_config) %}

{% do c.set_user(values.run_as.user, values.run_as.group) %}
{% do c.healthcheck.set_test("curl", {"port": values.network.web_port.port_number}) %}
{% do c.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}
{% do c.depends.add_dependency(values.consts.meilisearch_container_name, "service_healthy") %}

{% do c.environment.add_env("PORT", values.network.web_port.port_number) %}
{% do c.environment.add_env("DATABASE_URL", postgres.get_url("postgresql")) %}
{% do c.environment.add_env("NEXTAUTH_SECRET", values.linkwarden.nextauth_secret) %}
{% do c.environment.add_env("NEXTAUTH_INTERNAL_URL", "http://localhost:%d/api/v1/auth"|format(values.network.web_port.port_number)) %}
{% do c.environment.add_env("MEILI_MASTER_KEY", values.linkwarden.meilisearch_master_key) %}
{% do c.environment.add_env("MEILI_HOST", "http://%s:%d"|format(values.consts.meilisearch_container_name, values.consts.meilisearch_port)) %}
{% do c.environment.add_user_envs(values.linkwarden.additional_envs) %}

{% do c.add_port(values.network.web_port) %}

{% do c.add_storage("/data/data", values.storage.data) %}
{% do perm_container.add_or_skip_action("data", values.storage.data, perms_config) %}
{% set tmp_config = {"type": "temporary", "volume_config": {"volume_name": "tmp-cache"}} %}
{% do c.add_storage("/.yarn", tmp_config) %}
{% do c.add_storage("/.cache/yarn", tmp_config) %}
{% do perm_container.add_or_skip_action("tmp-cache", tmp_config, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do meili.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
