annotations:
  min_scale_version: 24.10.2.2
app_version: v2.11.5
capabilities: []
categories:
- productivity
changelog_url: https://github.com/linkwarden/linkwarden/releases
date_added: '2025-08-11'
description: Linkwarden is a self-hosted, open-source collaborative bookmark manager to collect, read, annotate, and fully preserve what matters, all in one place.
home: https://docs.linkwarden.app/
host_mounts: []
icon: missing
keywords:
- links
- bookmarks
lib_version: 2.1.35
lib_version_hash: 1bd4e0058fbd4d7c207df2cae606580065e8e6dba3e232f41bc1b006848b05d2
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: linkwarden
run_as_context:
- description: Linkwarden runs as any non-root user.
  gid: 568
  group_name: linkwarden
  uid: 568
  user_name: linkwarden
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
sources:
- https://docs.linkwarden.app/
- https://github.com/linkwarden/linkwarden
title: Linkwarden
train: community
version: 1.0.0
