app_version: v2.11.5
capabilities: []
categories:
- productivity
changelog_url: https://github.com/linkwarden/linkwarden/releases
date_added: '2025-08-11'
description: Linkwarden is a self-hosted, open-source collaborative bookmark manager
  to collect, read, annotate, and fully preserve what matters, all in one place.
home: https://docs.linkwarden.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/linkwarden/icons/icon.png
keywords:
- links
- bookmarks
lib_version: 2.1.45
lib_version_hash: 2b78b1918738cd8bbb292da9a3f5060f5122e085fa34559c5ae748ead981cff4
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: linkwarden
run_as_context:
- description: Linkwarden runs as any non-root user.
  gid: 568
  group_name: linkwarden
  uid: 568
  user_name: linkwarden
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
- description: Meilisearch runs as any non-root user.
  gid: 568
  group_name: meilisearch
  uid: 568
  user_name: meilisearch
screenshots: []
sources:
- https://docs.linkwarden.app/
- https://github.com/linkwarden/linkwarden
title: Linkwarden
train: community
version: 1.0.0
